<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #111827;
            font-size: 12px;
        }

        .header {
            border-bottom: 2px solid #2563eb;
            margin-bottom: 18px;
            padding-bottom: 10px;
        }

        .brand {
            color: #2563eb;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        h1 {
            margin: 6px 0;
            font-size: 22px;
        }

        .meta,
        .muted {
            color: #6b7280;
        }

        .summary {
            background: #eff6ff;
            border: 1px solid #bfdbfe;
            margin-bottom: 18px;
            padding: 12px;
        }

        .summary-title {
            color: #1e40af;
            font-weight: bold;
        }

        .summary-count {
            font-size: 24px;
            font-weight: bold;
        }

        table {
            border-collapse: collapse;
            width: 100%;
        }

        th,
        td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
        }

        th {
            background: #e5e7eb;
            font-weight: bold;
        }

        .name {
            font-weight: bold;
        }

        .empty {
            padding: 20px;
            text-align: center;
            color: #6b7280;
        }

        .footer {
            margin-top: 24px;
            color: #6b7280;
            font-size: 10px;
            text-align: center;
        }
    </style>
</head>
<body>
    @php
        $reportStudents = $students ?? collect();
    @endphp

    <div class="header">
        <div class="brand">Student Management System</div>
        <h1>{{ $title }}</h1>
        <div class="meta">Generated on {{ $date }}</div>
    </div>

    <div class="summary">
        <div class="summary-title">Total Students</div>
        <div class="summary-count">{{ $reportStudents->count() }}</div>
    </div>

    @if($reportStudents->count())
        <table>
            <thead>
                <tr>
                    <th style="width: 24%;">Full Name</th>
                    <th style="width: 23%;">Email</th>
                    <th style="width: 15%;">Contact</th>
                    <th style="width: 19%;">Degree</th>
                    <th style="width: 19%;">Image Path</th>
                </tr>
            </thead>
            <tbody>
                @foreach($reportStudents as $student)
                    <tr>
                        <td class="name">{{ $student->lname }}, {{ $student->fname }} {{ $student->mname }}</td>
                        <td>{{ $student->userAccount->email ?? $student->email ?? 'No email' }}</td>
                        <td>{{ $student->contactno ?? 'N/A' }}</td>
                        <td>{{ $student->degree?->degree_title ?? 'No Degree' }}</td>
                        <td>{{ $student->image_path ?? 'No image uploaded' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <div class="empty">No student records found.</div>
    @endif

    <div class="footer">
        Student report generated by Student Management System
    </div>
</body>
</html>
